version: "3"

services:
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: test-python
    volumes:
      - ./source:/home/source
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    tty: true
